apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: pibot-api:latest
      generation: null
      importPolicy: {}
      name: ""
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
