apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: filebeat
  name: filebeat
spec:
  replicas: 1
  selector:
    io.kompose.service: filebeat
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: filebeat
    spec:
      containers:
        - args:
            - --strict.perms=false
          env:
            - name: ELASTICSEARCH_HOST
              value: elasticsearch
          image: ' '
          name: filebeat
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/filebeat/filebeat.yml
              name: filebeat-claim0
            - mountPath: /usr/share/filebeat/data
              name: filebeat-claim1
            - mountPath: /var/run/docker.sock
              name: filebeat-claim2
            - mountPath: /var/lib/docker/containers/
              name: filebeat-claim3
              readOnly: true
            - mountPath: /var/log/
              name: filebeat-claim4
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: filebeat-claim0
          persistentVolumeClaim:
            claimName: filebeat-claim0
        - name: filebeat-claim1
          persistentVolumeClaim:
            claimName: filebeat-claim1
        - name: filebeat-claim2
          persistentVolumeClaim:
            claimName: filebeat-claim2
        - name: filebeat-claim3
          persistentVolumeClaim:
            claimName: filebeat-claim3
            readOnly: true
        - name: filebeat-claim4
          persistentVolumeClaim:
            claimName: filebeat-claim4
            readOnly: true
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - filebeat
        from:
          kind: ImageStreamTag
          name: filebeat:7.1.1
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
